# Key and Name
sonar.projectKey=react-bkoi-gl
sonar.projectName=react-bkoi-gl

# Source code   
sonar.sources=src

# Tests
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.ts, **/*.test.tsx

# Coverage reports
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.coverage.exclusions=**/node_modules/**, **/__tests__/**, **/src/types/**, **/*.d.ts,