#!/usr/bin/env node
/**
 * Bundles maplibre-gl's worker into ONE self-contained, Barikoi-branded file.
 *
 * Outputs:
 *  1. dist/bkoi-map-worker.mjs — shipped file (exports "./worker"); used when
 *     the consumer's bundler emits `new URL(..., import.meta.url)` assets
 *     (webpack 5 / CRA / Next.js). Contains the inlined maplibre-gl-shared
 *     chunk so a single emitted asset is complete (the upstream two-file
 *     layout breaks under Turbopack-style hashed asset emission).
 *  2. src/maplibre/worker-bundle.generated.ts — the same source inlined as a
 *     string; the library constructs a same-origin Blob worker from it when no
 *     asset was emitted (Vite dev pre-bundling, esbuild/Rollup, bare CJS).
 *     This is what makes the library zero-config in every bundler. The file is
 *     committed so `npm run typecheck` works before any build.
 *
 * `--ts-only` skips (1) — used before tsup, which needs the module present and
 * wipes dist/. The full run happens after tsup and rewrites both outputs.
 *
 * `legalComments: 'inline'` preserves the upstream BSD-3 license text inside
 * the bundle (redistribution attribution requirement).
 */
import esbuild from 'esbuild'
import { createRequire } from 'node:module'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = path.resolve(fileURLToPath(import.meta.url), '../..')
const require = createRequire(import.meta.url)
const workerEntry = path.join(
  path.dirname(require.resolve('maplibre-gl/package.json')),
  'dist',
  'maplibre-gl-worker.mjs'
)
const outfile = path.join(repoRoot, 'dist', 'bkoi-map-worker.mjs')
const declFile = path.join(repoRoot, 'dist', 'bkoi-map-worker.d.mts')
const generatedPath = path.join(repoRoot, 'src', 'maplibre', 'worker-bundle.generated.ts')

// The worker is a self-contained script consumed via `new Worker(new URL(...))`,
// never imported — this ambient declaration exists only so the `./worker`
// export resolves to types for TypeScript consumers and @arethetypeswrong.
const writeDecl = () => {
  fs.writeFileSync(
    declFile,
    `// GENERATED by scripts/build-worker.mjs — do not edit.\n// Worker script consumed via new Worker(new URL('react-bkoi-gl/worker', import.meta.url)).\nexport {}\n`
  )
}

const writeGenerated = (source) => {
  const generated = `/**
 * GENERATED by scripts/build-worker.mjs — do not edit.
 * Self-contained maplibre-gl v6 worker bundle, inlined so the library can
 * construct a same-origin Blob worker when the bundler did not emit an asset.
 * Committing this file keeps \`npm run typecheck\` working before a build.
 */
export const BKOI_WORKER_SOURCE = ${JSON.stringify(source)}
`
  fs.writeFileSync(generatedPath, generated)
  console.log(`[build-worker] inlined ${Math.round(source.length / 1024)}kb into worker-bundle.generated.ts`)
}

const bundle = async (target) =>
  esbuild.build({
    entryPoints: [workerEntry],
    outfile: target,
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'inline',
    sourcemap: false,
    logLevel: 'info',
  })

const tsOnly = process.argv.includes('--ts-only')

if (tsOnly) {
  // Regenerate the TS module only — bundle to a temp file so dist/ is untouched.
  if (!fs.existsSync(generatedPath)) {
    const tmp = path.join(os.tmpdir(), 'bkoi-map-worker.mjs')
    await bundle(tmp)
    writeGenerated(fs.readFileSync(tmp, 'utf8'))
    fs.rmSync(tmp)
  }
} else {
  await bundle(outfile)
  writeGenerated(fs.readFileSync(outfile, 'utf8'))
  writeDecl()
}
