// Runtime smoke for VERBATIM README examples — the second half of
// `npm run check:readme` (types there, execution here).
//
// ?case=readme-examples&example=Example03 mounts that single extracted
// example (tmp/readme-examples/, generated by scripts/check-readme-examples.mjs
// and always present under `npm run e2e`, which chains the extraction).
// The spec iterates the manifest; this page just mounts one and logs status.
import { useEffect, useRef } from 'react'
import { createRoot } from 'react-dom/client'

// Vite cannot dynamically import arbitrary variable paths — glob the extracted
// files instead and pick by URL param. Empty when extraction hasn't run.
const modules = import.meta.glob('../../../../tmp/readme-examples/Example*.{ts,tsx}')

export function ReadmeExamples() {
  const host = useRef(null)
  const rootRef = useRef(null)
  const exampleId = new URLSearchParams(location.search).get('example')

  useEffect(() => {
    if (!exampleId) return // browsable-index entry — hint rendered instead

    // Globals the examples assume a real app provides.
    window.BARIKOI_API_KEY = import.meta.env.BARIKOI_API_KEY
    window.Sentry = { captureMessage: () => {}, captureException: () => {} }
    window.process = {
      env: { BARIKOI_API_KEY: import.meta.env.BARIKOI_API_KEY, NODE_ENV: 'development' },
    }

    // StrictMode double-invokes effects: cancel the first (possibly still
    // awaiting) run at cleanup instead of leaking a second root on the host.
    let cancelled = false

    ;(async () => {
      try {
        const loader = Object.entries(modules).find(([p]) => p.endsWith(`/${exampleId}.tsx`))?.[1]
        if (!loader)
          throw new Error(`no extracted example "${exampleId}" — run npm run check:readme`)
        const mod = await loader()
        if (cancelled) return
        const Comp = mod.default ?? Object.values(mod)[0]
        rootRef.current ??= createRoot(host.current)
        rootRef.current.render(<Comp />)
        window.__log({ type: 'readme-example', id: exampleId, status: 'mounted' })
      } catch (e) {
        if (!cancelled)
          window.__log({ type: 'readme-example', id: exampleId, status: 'error', error: String(e) })
      }
    })()

    return () => {
      cancelled = true
      rootRef.current?.unmount()
      rootRef.current = null
    }
  }, [])

  if (!exampleId) {
    return (
      <div style={{ padding: 24, fontFamily: 'monospace' }}>
        <h2>Verbatim README examples</h2>
        <p>
          Each extracted README example mounts one per URL — this case is driven by
          <code> readme-examples.spec.ts</code> (part of <code>npm run e2e</code>). Browse manually
          with e.g. <code>/?case=readme-examples&amp;example=Example03</code> — ids live in{' '}
          <code>tmp/readme-examples/manifest.json</code> after <code>npm run check:readme</code>.
        </p>
      </div>
    )
  }

  return <div ref={host} style={{ width: '100vw', height: '100vh' }} />
}
