name: SonarQube Scan

on:
  push:
    branches: ['down'] # Temporary branch while SonarQube server is down - switch back to 'dev' when server is operational

env: 
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'

      - name: Install npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install 

      - name: Run tests with coverage
        run: npm run coverage              

      - name: Run SonarQube Scannner
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=react-bkoi-gl
            -Dsonar.projectName=react-bkoi-gl
            -Dsonar.sources=src
            -Dsonar.tests=__tests__
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.coverage.exclusions=**/node_modules/**,**/__tests__/**,**/src/types/**,**/*.d.ts

      - name: Workflow Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          username: react-bkoi-gl
          severity: info
          details: "The SonarQube scan was successful without any issues."
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}

      - name: Workflow Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          username: react-bkoi-gl
          severity: error
          details: Workflow Failed!
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}

      - name: Workflow Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          username: react-bkoi-gl
          severity: warn
          details: Workflow Cancelled!
          webhookUrl: ${{ env.DISCORD_WEBHOOK }}